using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Pages.Shared.Models
{
    public class CompressorInfo
    {

        [Key]//Primary Key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] //Autogenerated ID
        public int ID { get; set; } 
        public DateTime? CompressDate { get; set; }
        public string? Compressor { get; set; }
        public double? GasRate { get; set; }
        public int? Downtime { get; set; }
        public string? Comments { get; set; }
    }
}